enum CommandID {
    CommandName_ID,
    SpecName_ID,
    SpecPrefix_ID,
    cancel_ID,
    caret_move_character_next_ID,
    caret_move_character_previous_ID,
    caret_move_end_ID,
    caret_move_line_end_ID,
    caret_move_line_next_ID,
    caret_move_line_previous_ID,
    caret_move_line_start_ID,
    caret_move_page_next_ID,
    caret_move_page_previous_ID,
    caret_move_start_ID,
    caret_move_token_next_ID,
    caret_move_token_previous_ID,
    caret_select_character_next_ID,
    caret_select_character_previous_ID,
    caret_select_end_ID,
    caret_select_line_end_ID,
    caret_select_line_next_ID,
    caret_select_line_previous_ID,
    caret_select_line_start_ID,
    caret_select_page_next_ID,
    caret_select_page_previous_ID,
    caret_select_start_ID,
    caret_select_token_next_ID,
    caret_select_token_previous_ID,
    close_ID,
    confirm_ID,
    delete_character_next_ID,
    delete_character_previous_ID,
    find_text_ID,
    modal_test_ID,
    new_ID,
    next_view_ID,
    open_ID,
    panel_1_focus_ID,
    panel_2_focus_ID,
    quit_ID,
    redo_ID,
    save_ID,
    select_all_ID,
    select_next_ID,
    shell_focus_ID,
    tabulate_ID,
    undo_ID,
    workspace_build_ID,
    zoom_in_ID,
    zoom_out_ID,
};

String COMMAND_NAMES[] = {
    [CommandName_ID] = { .items = "CommandName", .count = 11 },
    [SpecName_ID] = { .items = "SpecName", .count = 8 },
    [SpecPrefix_ID] = { .items = "SpecPrefix", .count = 10 },
    [cancel_ID] = { .items = "cancel", .count = 6 },
    [caret_move_character_next_ID] = { .items = "caret.move.character.next", .count = 25 },
    [caret_move_character_previous_ID] = { .items = "caret.move.character.previous", .count = 29 },
    [caret_move_end_ID] = { .items = "caret.move.end", .count = 14 },
    [caret_move_line_end_ID] = { .items = "caret.move.line.end", .count = 19 },
    [caret_move_line_next_ID] = { .items = "caret.move.line.next", .count = 20 },
    [caret_move_line_previous_ID] = { .items = "caret.move.line.previous", .count = 24 },
    [caret_move_line_start_ID] = { .items = "caret.move.line.start", .count = 21 },
    [caret_move_page_next_ID] = { .items = "caret.move.page.next", .count = 20 },
    [caret_move_page_previous_ID] = { .items = "caret.move.page.previous", .count = 24 },
    [caret_move_start_ID] = { .items = "caret.move.start", .count = 16 },
    [caret_move_token_next_ID] = { .items = "caret.move.token.next", .count = 21 },
    [caret_move_token_previous_ID] = { .items = "caret.move.token.previous", .count = 25 },
    [caret_select_character_next_ID] = { .items = "caret.select.character.next", .count = 27 },
    [caret_select_character_previous_ID] = { .items = "caret.select.character.previous", .count = 31 },
    [caret_select_end_ID] = { .items = "caret.select.end", .count = 16 },
    [caret_select_line_end_ID] = { .items = "caret.select.line.end", .count = 21 },
    [caret_select_line_next_ID] = { .items = "caret.select.line.next", .count = 22 },
    [caret_select_line_previous_ID] = { .items = "caret.select.line.previous", .count = 26 },
    [caret_select_line_start_ID] = { .items = "caret.select.line.start", .count = 23 },
    [caret_select_page_next_ID] = { .items = "caret.select.page.next", .count = 22 },
    [caret_select_page_previous_ID] = { .items = "caret.select.page.previous", .count = 26 },
    [caret_select_start_ID] = { .items = "caret.select.start", .count = 18 },
    [caret_select_token_next_ID] = { .items = "caret.select.token.next", .count = 23 },
    [caret_select_token_previous_ID] = { .items = "caret.select.token.previous", .count = 27 },
    [close_ID] = { .items = "close", .count = 5 },
    [confirm_ID] = { .items = "confirm", .count = 7 },
    [delete_character_next_ID] = { .items = "delete.character.next", .count = 21 },
    [delete_character_previous_ID] = { .items = "delete.character.previous", .count = 25 },
    [find_text_ID] = { .items = "find.text", .count = 9 },
    [modal_test_ID] = { .items = "modal.test", .count = 10 },
    [new_ID] = { .items = "new", .count = 3 },
    [next_view_ID] = { .items = "next.view", .count = 9 },
    [open_ID] = { .items = "open", .count = 4 },
    [panel_1_focus_ID] = { .items = "panel.1.focus", .count = 13 },
    [panel_2_focus_ID] = { .items = "panel.2.focus", .count = 13 },
    [quit_ID] = { .items = "quit", .count = 4 },
    [redo_ID] = { .items = "redo", .count = 4 },
    [save_ID] = { .items = "save", .count = 4 },
    [select_all_ID] = { .items = "select.all", .count = 10 },
    [select_next_ID] = { .items = "select.next", .count = 11 },
    [shell_focus_ID] = { .items = "shell.focus", .count = 11 },
    [tabulate_ID] = { .items = "tabulate", .count = 8 },
    [undo_ID] = { .items = "undo", .count = 4 },
    [workspace_build_ID] = { .items = "workspace.build", .count = 15 },
    [zoom_in_ID] = { .items = "zoom.in", .count = 7 },
    [zoom_out_ID] = { .items = "zoom.out", .count = 8 },
};
